import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { PokemonProvider } from "@/context/PokemonContext";

const montserrat = Montserrat({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <PokemonProvider>
      <html lang="en">
        <body className={`${montserrat.className} antialiased`}>
          {children}
        </body>
      </html>
    </PokemonProvider>
  );
}
